sudo: false
language: cpp
compiler: clang
os: linux
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - g++-6
            - clang-5.0

matrix:
  include:
    - env:
        BUILD_TYPE=Debug
        BIN_DIR=debug
        CC=clang-5.0
        CXX=clang++-5.0
    - env:
        BUILD_TYPE=Release
        BIN_DIR=bin
        CC=clang-5.0
        CXX=clang++-5.0
script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
    - make -j
    - ../$BIN_DIR/projet_lzw -c -i ../$BIN_DIR/projet_lzw
