sudo: false
language: cpp
compiler: clang
os: linux
dist: trusty
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
        packages:
            - g++-7
            - clang-5.0

matrix:
  include:
    # Linux Clang C++17
    - env:
        BUILD_TYPE=Debug
        BIN_DIR=debug
        CC=clang-5.0
        CXX=clang++-5.0
    - env:
        BUILD_TYPE=Release
        BIN_DIR=bin
        CC=clang-5.0
        CXX=clang++-5.0

    # Linux GCC C++17
    - env:
        - MATRIX_EVAL="BUILD_TYPE=Debug && BIN_DIR=debug && CC=gcc-7 && CXX=g++-7"
      compiler: gcc
      before_install:
        - eval "${MATRIX_EVAL}"
    - env:
        - MATRIX_EVAL="BUILD_TYPE=Release && BIN_DIR=bin && CC=gcc-7 && CXX=g++-7"
      compiler: gcc
      before_install:
        - eval "${MATRIX_EVAL}"

    # OSX Clang
    - os: osx
      osx_image: xcode8
      env:
        BUILD_TYPE=Release
        BIN_DIR=bin
      before_install:
        brew update
      install:
        brew upgrade cmake
    - os: osx
      osx_image: xcode8
      env:
        BUILD_TYPE=Debug
        BIN_DIR=debug
      before_install:
        brew update
      install:
        brew upgrade cmake
script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
    - make -j
    - ../$BIN_DIR/projet_lzw -c -i ../$BIN_DIR/projet_lzw
