language: cpp
os: linux
dist: trusty

matrix:
  include:
    - env:
        - CC=clang-5.0
          CXX=clang++-5.0
          BUILD_TYPE=Release
          BIN_DIR=bin
        addons: &clang40
          apt:
            packages:
              - g++-5
              - clang-5.0
            sources:
              - ubuntu-toolchain-r-test
              - llvm-toolchain-trusty-5.0
              - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-4.0 main'
                key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
    - env:
        - CC=clang-5.0
        - CXX=clang++-5.0
        - BUILD_TYPE=Release
        - BIN_DIR=bin
      addons: *clang40

script:
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD ..
  - make -j
  - ../$BINDIR/projet_lzw -c -i ../$BINDIR/projet_lzw
