sudo: false
language: cpp
compiler: clang
os: linux
dist: trusty

matrix:
  include:
    - script:
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make -j
    - script:
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make -j


            
notifications:
  email:
    - phundrak@phundrak.fr
