sudo: false
language: cpp

matrix:
  include:
    - os: linux
      dist: trusty
      compiler: g++
      script:
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make -j
    - os: linux
      dist: trusty
      compiler: clang
      script:
        - cd build
        - cmake --version
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make -j
    - os: linux
      dist: trusty
      compiler: g++
      script:
        - cd build
        - cmake --version
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make -j
    - os: linux
      dist: trusty
      compiler: clang
      script:
        - cd build
        - cmake --version
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make -j

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-6.3

notifications:
  email:
    - phundrak@phundrak.fr
