language: cpp

matrix:
    include:
        - os: linux
          dist: trusty
          compiler: clang
          env:
            - CC=clang
            - CXX=clang++
            - BUILDTYPE=Release
            - BINDIR=bin
        - os: linux
          dist: trusty
          compiler: clang
          env:
            - CC=clang
            - CXX=clang++
            - BUILDTYPE=Debug
            - BINDIR=debug
        - os: linux
          dist: trusty
          compiler: gcc
          addons: &gcc7
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - cmake3
                    - g++7
                    - gcc7
          env:
            - CC=gcc7
            - CXX=g++7
            - BUILDTYPE=Release
            - BINDIR=bin
        - os: linux
          dist: trusty
          compiler: gcc
          addons: &gcc7
            apt:
                sources:
                    - ubuntu-toolchain-r-test
                packages:
                    - cmake3
                    - g++7
                    - gcc7
          env:
            - CC=gcc7
            - CXX=g++7
            - BUILDTYPE=Debug
            - BINDIR=debug

script:
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=$BUILD ..
    - make -j
    - ../$BINDIR/projet_lzw -c -i ../$BINDIR/projet_lzw
