sudo: false
language: cpp
compiler: clang
os: linux
dist: trusty

matrix:
  include:
    - script:
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Debug ..
        - make -j
        - ../debug/projet_lzw -c -i ../debug/projet_lzw
    - script:
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make -j
        - ../bin/projet_lzw -c -i ../bin/projet_lzw

notifications:
  email:
    - phundrak@phundrak.fr
