version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:16.04-curl-browsers
    environment:
      - PATH: "$PATH:$HOME/.yarn/bin"
      - CXX: g++-7.1
    steps:
      - checkout
      - run: sudo add-apt-repository -y ppa:jonathonf/gcc-7.1
      - run: sudo apt-get update
      - run: sudo apt-get install gcc-7 g++-7
      - run:
          name: Build cmake
          command: |
            cd ~ && wget --quiet https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz
            tar -xvf cmake-3.11.0-Linux-x86_64.tar.gz
      - run:
          name: Build Project
          command: cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j
