version: 2
jobs:
  build:
    docker:
      - image: rikosote/gcc-cmake:latest
#       - image: madduci/docker-ubuntu-cpp:gcc-6
#      - image: buildpack-deps:trusty
    environment:
      - PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    steps:
      - checkout
      - run: gcc --version
      - run: cmake --version
#      - run: sudo apt-get install software-properties-common python-software-properties
#      - run: sudo add-apt-repository -y ppa:jonathonf/gcc-7.1
#      - run: sudo apt-get update
#      - run: sudo apt-get install gcc-7 g++-7
      - run:
          name: Build cmake
          command: |
            cd ~ && wget --quiet https://cmake.org/files/v3.11/cmake-3.11.0-Linux-x86_64.tar.gz
            tar -xvf cmake-3.11.0-Linux-x86_64.tar.gz
      - run:
          name: Build Project
          command: cd build && cmake -DCMAKE_BUILD_TYPE=Debug .. && make -j
